### ISSUE TITLE
Error in installing package from Maven

### ISSUE THREAD

**Issue by xie-qianyue** [opensourceBIM/DemoPlugins#2]
I have a problem of installing package `org.opensourcebim.shared`, because its version has a suffix "SNAPSHOT" which it doesn't contain in the [Maven repo](https://mvnrepository.com/artifact/org.opensourcebim/shared/1.5.71).

```
<dependency>
	<groupId>org.opensourcebim</groupId>
	<artifactId>shared</artifactId>
	<version>1.5.71-SNAPSHOT</version>
</dependency>
```

I also find that there is already a [PR](https://github.com/opensourceBIM/DemoPlugins/pull/1) for this problem. May you merge this PR?

**Comment by rubendel** [comment]
I don't understand what you mean with "installing package org.opensourcebim.shared", how do you install a Java package?

It contains SNAPSHOT because in development mode (which the GIT repository always is) is assumes you also have a BIMserver checked out (in SNAPSHOT mode as well).

**Comment by xie-qianyue** [comment]
I lauch the project's maven build. There is an error during the building process:

```
[ERROR] Failed to execute goal on project demoplugins: Could not resolve dependencies for project org.opensourcebim:demoplugins:jar:0.0.17-SNAPSHOT: Failure to find org.opensourcebim:shared:jar:1.5.71-SNAPSHOT in http://uk.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of uk.maven.org has elapsed or updates are forced -> [Help 1]
```

What I understand this log, is that maven try to install/download the "org.opensourcebim.shared" package, but it failed. Because the package is not present in the maven repo.

So I tried to find out this package in the maven repo, I found [this package](https://mvnrepository.com/artifact/org.opensourcebim/shared/1.5.71), but its version is 1.5.71.

I have BIMServer checked out, but in the class for example, GeometryInfoToExcelPlugin.java, it can't reach `org.bimserver.plugins.services.AbstractAddExtendedDataService` if 'org.opensourcebim.shared' isn't resolved by Maven.

**Comment by rubendel** [comment]
The version number has to match the version of your bimserver. If your BIMserver checkout is up-to-date it should be 1.5.78-SNAPSHOT so put that in there and it should work. When building however you cannot reference SNAPSHOT dependencies so you should change that to a recently released version with which it will compile (for example 1.5.77).

Reading a little about maven probably would help understand the SNAPSHOT stuff a little better.

**Comment by xie-qianyue** [comment]
Thank you for the tips. Because my BIMserver version is not up-to-date.
